master:
  push:
    - services:
      - github-actions
      stages:
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x'
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: '1.9.1+hotfix.6'
        - run: flutter pub get
        - run: flutter test
        - run: flutter create .
        - run: rm test/widget_test.dart
        - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            # Artifact name
            name: apks
            # Directory containing files to upload
            path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk

        - run: flutter test --coverage
#        - name: codecov
#          uses: codecov/codecov-action@v1.0.5
#          with:
#            # User defined upload name. Visible in Codecov UI
#            name: coverage
#            # Repository upload token - get it from codecov.io
#            token: ${{secrets.CODECOV_TOKEN}}
#            # Path to coverage file to upload
#            file: ./coverage/lcov.info
#            # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
#            flags: unittests# optional
#            # Specify whether or not CI build should fail if Codecov runs into an error during upload
#            fail_ci_if_error: false # optional
